name: gerrymi
favicon: null
layout_spectrum: 0.088623964227736
typography_spectrum: 0.69312
title: musings of a mad man
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131019'
    - '#c7c7bf'
    - '#ff6d80'
    - '#4f4c3d'
    - '#66c4fa'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
